import NewsAlert from "@/components/news-alert";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "./auth-provider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <NewsAlert />
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
